# Generated by Django 4.0.4 on 2022-05-15 16:58

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cidade', models.IntegerField()),
                ('nome_cidade', models.CharField(max_length=50)),
                ('id_uf', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_conta', models.IntegerField()),
                ('tp_conta', models.CharField(max_length=30)),
                ('id_banco', models.IntegerField()),
                ('banco', models.CharField(max_length=50)),
                ('conta', models.IntegerField()),
                ('agencia', models.IntegerField()),
                ('operacao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_endereco', models.IntegerField()),
                ('id_cidade', models.IntegerField()),
                ('logradouro', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=8)),
                ('cep', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=80)),
                ('complemento', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ocorrencia', models.IntegerField()),
                ('data', models.DateField(blank=True, null=True)),
                ('realizada', models.CharField(max_length=1)),
                ('id_pessoa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pessoa', models.IntegerField()),
                ('vinculo', models.CharField(max_length=20)),
                ('cpf', cpf_field.models.CPFField(max_length=14, verbose_name='cpf')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=200)),
                ('id_endereco', models.IntegerField()),
                ('id_conta', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='uf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_uf', models.IntegerField()),
                ('nome_uf', models.CharField(max_length=30)),
                ('sigla_uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('username', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
    ]
