# Generated by Django 4.0.4 on 2022-05-16 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='ocorrencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='id_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projeto.user'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='id_uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projeto.uf'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='id_cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projeto.cidade'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='id_pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projeto.pessoa'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='id_conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projeto.conta'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='id_endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projeto.endereco'),
        ),
    ]
