# Generated by Django 4.0.6 on 2022-07-16 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0002_endereco_observacoes_ocorrencia_ocorrencia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user_name',
        ),
    ]
